apiVersion: v1
kind: Service
metadata:
  labels:
    app: tomcat-cicd
  name: service
  namespace: default
spec:
  ports:
  - nodePort: 31366
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat-cd
  type: NodePort
